### ISSUE TITLE
Implementar controle de acesso de funcionário e gerente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#102]
- Codificar o controle conforme [RNF01]

**Comment by thiagorainmaker77** [comment]
@fabianaferreiracardoso preciso de uma listas das telas que somente o gerente terá acesso e das telas que somente o funcionário terá acesso.

@Mars17 para o primeiro acesso sugiro que o usuário logue com seu CPF como login e senha; Ok?

**Comment by fabianaferreiracardoso** [comment]
Marcelo por gentileza providenciar as informações necessárias para que o
Arquiteto Desenvolvedor possar continuar o desenvolvimento da
funcionaldiade.

Em ter, 29 de jan de 2019 às 10:09, Thiago Fernandes <
notifications@github.com> escreveu:

**Comment by thiagorainmaker77** [comment]
@Mars17 @fabianaferreiracardoso  no momento já foi implementado o acesso de funcionário: que loga com o cpf de cadastro, e do administrador.

Fico no aguardo da definição das restrições de telas;

**Comment by Mars17** [comment]
Sumário: O Usuario entra no sistema com as credenciais de acesso, login e senha.
Ator Principal: Administrador e Funcionário
Pré Condições: O Usuário está pré-cadastrado no sistema
Fluxo Principal: 
O usuário acessa a pagina, site, do sistema.
O sistema abre a interface solicitando o login e senha do usuário.
O usuário preenche com suas credenciais de acesso.
O sistema trata os dados e disponibiliza o acesso ao sistema, o caso de uso chega ao fim.

Fluxo Alternativo: Não há.
Fluxo de Exceções: Campo obrigatório vazio.
Caso o usuário não preencher os campos obrigatorios o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Usuário não cadastrado.
Caso o usuário não esteja cadastrado na base de dados do sistema o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Usuário não cadastrado.
Caso o usuário não esteja cadastrado na base de dados do sistema o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Dado Incorreto.
Caso o usuário preencha com alguma das credenciais incorreta o sistema exibirá  uma mensagem de erro e retornará a etapa 2.
Pós Condições: O usuário conseguiu acesso ao Sistema.

**Comment by Mars17** [comment]
**Sumário:** O Usuario entra no sistema com as credenciais de acesso, login e senha.

**Ator Principal:** Administrador e Funcionário

**Pré Condições:** O Usuário está pré-cadastrado no sistema

**Fluxo Principal:** 
O usuário acessa a pagina, site, do sistema.
O sistema abre a interface solicitando o login e senha do usuário.
O usuário preenche com suas credenciais de acesso.
O sistema trata os dados e disponibiliza o acesso ao sistema, o caso de uso chega ao fim.

Fluxo Alternativo: Não há.
Fluxo de Exceções: Campo obrigatório vazio.
Caso o usuário não preencher os campos obrigatorios o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Usuário não cadastrado.
Caso o usuário não esteja cadastrado na base de dados do sistema o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Usuário não cadastrado.
Caso o usuário não esteja cadastrado na base de dados do sistema o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Dado Incorreto.
Caso o usuário preencha com alguma das credenciais incorreta o sistema exibirá  uma mensagem de erro e retornará a etapa 2.
Fluxo de Exceções: Funcionario Inativo.
Caso o usuário não esteja com o cadastrado de status ativo o caso de uso exibirá uma mensagem de erro e retornará a etapa 2.

**Pós Condições:** O usuário conseguiu acesso ao Sistema.
