### ISSUE TITLE
Criar artefatos de análise e design para o requisito não funcional [RNF01] - Controle de acesso de funcionário e gerente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#103]
- Realizar a análise e criar os artefatos de users stories, diagramas de caso de uso, diagrama de classe e sequência.

**Comment by fabianaferreiracardoso** [comment]
Realizar a análise para implementação do requisito não funcional [RNF 01]

O sistema deve controlar o acesso às funcionalidades. Funcionalidades para controlar o acervo da locadora devem ser restritas a administradores. Funcionalidades de atendimento a clientes devem estar restritas a atendentes. Funcionalidades de consulta ao acervo devem estar disponíveis na Internet.

**Comment by Mars17** [comment]
Boa noite @fabianaferreiracardoso ! É necessário nesse issue, fazer um diagrama de Classe só pra esse controle acesso?

**Comment by fabianaferreiracardoso** [comment]
Artefato disponibilizado no driver
