### ISSUE TITLE
Revisar e atualizar artefatos de requisitos de negócio

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#110]
Revisar e caso seja necessário atualizar users stories e casos de uso para:

- CRUD de filme, cliente e funcionário.
- Locação de filme
- Controle de acesso à funcionalidades do sistema

**Comment by fabianaferreiracardoso** [comment]
A revisão de deverá contemplar tudo o que foi apresentado no documento de requisitos fornecido pelo cliente.

[Documento de Requisitos - MPROF - Video Locadora Imperial.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2821833/Documento.de.Requisitos.-.MPROF.-.Video.Locadora.Imperial.pdf)

[Proposta de Projeto - Ciclo de Vida do Software.docx](https://github.com/thiagorainmaker77/blockbuster/files/2821839/Proposta.de.Projeto.-.Ciclo.de.Vida.do.Software.docx)

**Comment by fabianaferreiracardoso** [comment]
Por gentileza inserir os artefatos comprovando o encerramento da revisão.

**Comment by fabianaferreiracardoso** [comment]
Prazo para inserção dos artefatos: 04/02/2019

**Comment by fabianaferreiracardoso** [comment]
A funcionalidade controle de acesso deverá abordar a autenticacao de clientes via google

**Comment by fabianaferreiracardoso** [comment]
Inserir os artefatos de disponibilização do acervo de filmes via Internet

**Comment by fabianaferreiracardoso** [comment]
[Documento_de_Requisitos_Users_Stories_Blockbuster_08_02_2019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2867489/Documento_de_Requisitos_Users_Stories_Blockbuster_08_02_2019.pdf)

**Comment by fabianaferreiracardoso** [comment]
Marcello por favor corrigir os atores dos casos de uso Gerente para Administrador, Funcionário para atendente.

Acrescente o caso de uso distribuidora e cadastro de funcionário no diagrama

Revise o artefato de casos de uso, falta inserir pesquisa acervo e distribuidora.

**Comment by fabianaferreiracardoso** [comment]
[Documento_Requisitos_Casos_Uso_13_02_2018.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2867759/Documento_Requisitos_Casos_Uso_13_02_2018.pdf)

**Comment by fabianaferreiracardoso** [comment]
[Documento_de_Requisitos_Users_Stories_Blockbuster_08_02_2019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2872110/Documento_de_Requisitos_Users_Stories_Blockbuster_08_02_2019.pdf)

**Comment by fabianaferreiracardoso** [comment]
[Documento_de_Requisitos_Users_Stories_17_02_2019.docx](https://github.com/thiagorainmaker77/blockbuster/files/2872814/Documento_de_Requisitos_Users_Stories_17_02_2019.docx)

**Comment by Mars17** [comment]
> Marcello por favor corrigir os atores dos casos de uso Gerente para Administrador, Funcionário para atendente.
> 
> Acrescente o caso de uso distribuidora e cadastro de funcionário no diagrama
> 
> Revise o artefato de casos de uso, falta inserir pesquisa acervo e distribuidora.

Ja existia a Pesquisa em acervo
![telas de acesso e responsabilidades 3](https://user-images.githubusercontent.com/7024700/52922488-77891580-3300-11e9-9d16-0528e7a6c4e9.jpeg)

**Comment by Mars17** [comment]
[DS - Projeto.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2876960/DS.-.Projeto.pdf)
