### ISSUE TITLE
Revisar e atualizar artefatos de modelagem, análise e design (Diagrama de Sequência)

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#111]
- Revisar e caso seja necessário atualizar todos os artefatos que fazem parte da disciplina de modelagem, análise e design do software contemplando tudo o que consta no documento de requisitos fornecido pelo professor.

**Comment by fabianaferreiracardoso** [comment]
Nessa revisão deverão ser observados:
1. Coerência dos artefatos com users stories e casos de uso apresentados na disciplina de requisitos

**Comment by fabianaferreiracardoso** [comment]
Deverão ser entregues artefatos referentes às funcionalidade definidas no projeto inclusive o controle de acesso.
- Diagrama de Sequência de Filme
- Diagrama de Sequência de Cliente
- Diagrama de Sequência de Locação de Filme
- Diagrama de Sequência de Controle de Acesso
- Diagrama de Sequência de Funcionário

**Comment by fabianaferreiracardoso** [comment]
Prazo para inserção dos artefatos: 04/02/2019

**Comment by fabianaferreiracardoso** [comment]
Inserir a autenticação de cliente via google

**Comment by fabianaferreiracardoso** [comment]
Inserir a disponibilização do acervo de filmes via Internet

**Comment by Mars17** [comment]
Diagrama de Sequência de Filme - Conferido
![diagrama de sequencia basico 9](https://user-images.githubusercontent.com/7024700/52184440-54d40880-27fa-11e9-9589-44a33405988b.jpeg)
![ds-atualizacao filme](https://user-images.githubusercontent.com/7024700/52184504-315d8d80-27fb-11e9-8b05-274d27126337.png)
![ds-exccusao de filme](https://user-images.githubusercontent.com/7024700/52184506-33275100-27fb-11e9-86c6-b57509b8db8d.png)

**Comment by Mars17** [comment]
**Diagrama de Sequência de Cliente** - Conferido
![diagrama de sequencia basico 10](https://user-images.githubusercontent.com/7024700/52185350-f0b74180-2805-11e9-9b38-cbba9a0d7480.jpeg)

**Considerando que para Adicionar Clientes (independente de ser titular ou dependente) necessitará ser maior de idade e no cado cado especifico do titular, haverá a possibilidade de inclusão de apenas 3 dependentes.**

![diagrama de sequencia basico 11](https://user-images.githubusercontent.com/7024700/52185753-cd8e9100-2809-11e9-8979-7a2083a083ae.jpeg)
![ds- exclusao cliente](https://user-images.githubusercontent.com/7024700/52185752-cd8e9100-2809-11e9-9e3b-17919b95468a.jpeg)

**Comment by Mars17** [comment]
Atendendo RF10 - Atualização Cadastral Cliente - Desativar Clientes
![diagrama de sequencia basico 12](https://user-images.githubusercontent.com/7024700/52186993-f155d500-2811-11e9-8784-71f4c6e490bd.jpeg)

**Comment by Mars17** [comment]
Diagrama de Sequência de Filme - Conferido
![diagrama de sequencia basico 9](https://user-images.githubusercontent.com/7024700/52187768-7d69fb80-2816-11e9-983f-8df08bc95eb7.jpeg)

![ds-exccusao de filme](https://user-images.githubusercontent.com/7024700/52187754-6a572b80-2816-11e9-9c69-d1e3d699faf7.png)

![ds-atualizacao filme](https://user-images.githubusercontent.com/7024700/52187755-6a572b80-2816-11e9-9ec3-012085c2f8a5.png)

**Comment by Mars17** [comment]
Diagrama de Sequência de Funcionario
![ds- cadastro funcionario](https://user-images.githubusercontent.com/7024700/52187816-aee2c700-2816-11e9-90ad-efcb22480782.jpeg)
![Uploading DS- Exclusão Funcionario.jpeg…]()
![Uploading DS-Atualização Funcionario.jpeg…]()


 - Conferido

**Comment by Mars17** [comment]
![ds- exclusao funcionario](https://user-images.githubusercontent.com/7024700/52187885-fff2bb00-2816-11e9-8167-64fd48efe702.jpeg)
![ds-atualizacao funcionario](https://user-images.githubusercontent.com/7024700/52187886-fff2bb00-2816-11e9-960c-a0eabcdc13f9.jpeg)

**Comment by Mars17** [comment]
![diagrama de sequencia basico 16](https://user-images.githubusercontent.com/7024700/52250682-187ad800-28e0-11e9-9058-28af8c655af7.jpeg)

**Comment by Mars17** [comment]
sem desconto e com data de devolucao padrao
![ds - sem desconto e com data de devolucao padrao](https://user-images.githubusercontent.com/7024700/52313845-43743300-2997-11e9-8731-afa42405cd21.jpeg)

Aplicação de desconto e ampliação da data de devolução
![diagrama de sequencia basico 19](https://user-images.githubusercontent.com/7024700/52313846-44a56000-2997-11e9-846d-d8c2c61c6b3e.jpeg)

**Comment by thiagorainmaker77** [comment]
@Mars17 as sequencias do diagrama pedem para programar os seguintes caminhos:

CAMINHO 1

cliente solicita locação de filme > funcionario pergunta qual midia> cliente escolhe as mídias > funcionario verifica disponibilidade > sistema checa disponibilidade

depois disso o sistema da as seguintes resposatas:

> exceção: indisponibilidade de mídia
> exceção: midia reservada
> exceção: cliente em atraso
> cliente não cadastrado

depois disso (mesmo com as mensagens acima):
> sistema calcula o valor da locação
> sistema gera a data de decolução
> o funcionário informa o valor para o cliente
> o funcionário avisa o valor e a data de decolução para o cliente
> o funcionário efetua a locação

---------------------------------------------------

CAMINHO 2

cliente solicita locação de filme > funcionario pergunta qual midia> cliente escolhe as mídias > funcionario verifica disponibilidade > sistema checa disponibilidade

depois disso o sistema da as seguintes resposatas:

> exceção: indisponibilidade de mídia
> exceção: midia reservada
> exceção: cliente em atraso
> cliente não cadastrado

depois disso (mesmo com as mensagens acima):
> funcionário inseri desconto
> sistema recalcula valor
> sistema gera data de devolução
>funcionário informa valor (mesmo sem obter a resposta do sistema)
> funcionário amplia data de devolução (mesmo sem a resposta do sistema)
>funcionário informa a data de devoluão para o cliente
> funcionário efetua a locação

--------------------------------------------------------------


Ta certo isso? se sim, mova a tarefa para feito que irei começar a implementação hj a noite

**Comment by Mars17** [comment]
![ds - sem desconto e com data de devolucao padrao 3](https://user-images.githubusercontent.com/7024700/52384283-fd38d580-2a63-11e9-8fea-7b1558083e66.jpeg)
![diagrama de sequencia basico 21](https://user-images.githubusercontent.com/7024700/52384284-fd38d580-2a63-11e9-81c7-f875c50541eb.jpeg)

**Comment by thiagorainmaker77** [comment]
![captura de tela de 2019-02-07 08-20-06](https://user-images.githubusercontent.com/44616457/52405245-00f34900-2ab2-11e9-889a-6e9f20e35349.png)
@Mars17  conforme demonstro no desenho, ainda ha erros na sequência apresentada.

**Comment by Mars17** [comment]
Bom dia, @thiagorainmaker77 acompanhe os números sequenciais, perceba que os número tem uma sequência, dessa Sequência comtempla o que você falou acima

**Comment by thiagorainmaker77** [comment]
@Mars17 Ok, entendido.

**Comment by Mars17** [comment]
![diagrama de sequencia basico 1](https://user-images.githubusercontent.com/7024700/52884638-a3b46300-3155-11e9-8e56-63decd136418.png)
Acrescentando o Diagrama de Sequencia - Cadastro do Diagrama de Distribuidoras

**Comment by Mars17** [comment]
![diagrama de sequencia basico 3](https://user-images.githubusercontent.com/7024700/52968901-7651fa00-338d-11e9-90d4-bf7f42a37d8b.jpeg)

Atualização Distribuidora
