### ISSUE TITLE
Revisar e atualizar artefatos de modelagem (Diagrama de Classe)

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#112]
- Validar o diagrama de classe com os artefatos gerados na disciplina de requisitos

**Comment by fabianaferreiracardoso** [comment]
Inserir o artefato Diagrama de Classe contemplando as classes, atributos, métodos e relacionamentos coerentes com a etapa de requisitos.
No diagrama deverá estar cliente, filme, controle de acesso, funcionário etc

**Comment by fabianaferreiracardoso** [comment]
O Prazo para inserção dos artefatos: 04/02/2019

**Comment by Mars17** [comment]
![untitled diagram 3](https://user-images.githubusercontent.com/7024700/52136197-aaf45080-262e-11e9-99cb-7c1f0ff9f472.jpg)


Atualizado conforme a atual realidade do sistema junto as regras de negocio de Cadastro Funcionario, Cliente, Filme e Locação

**Comment by fabianaferreiracardoso** [comment]
Verificar como ficará o controle de autenticação de cliente via google

**Comment by Mars17** [comment]
Mas isso dentro do diagrama?

**Comment by Mars17** [comment]
Inclusão de Atributo Boolean Lancamento na entidade Filme....considerar posteriormente para calculo de Locação de itens lançamentos ou calculo. Atender Requisito RN11
![diagrama classes](https://user-images.githubusercontent.com/7024700/52186253-607cfa80-280d-11e9-9117-15a36e740a02.jpg)

**Comment by Mars17** [comment]
Diagrama atualizado
![untitled diagram 3 2](https://user-images.githubusercontent.com/7024700/52317115-c8664900-29a5-11e9-92d9-13ec73adaa24.jpg)

As Entidade Filme, mudou de nome para Item conforme sugerido no documento de requisitos, acresceu tbm a Entidade Distribuidora a ser implementada

**Comment by thiagorainmaker77** [comment]
@Mars17 a entidade Filme foi substituída pela entidade Item? se sim, mova a tarefa para feito que irei começar a implementação;

**Comment by fabianaferreiracardoso** [comment]
![diagramaclassefev](https://user-images.githubusercontent.com/45265644/52792817-6bc4f700-3053-11e9-801e-23fe2538f5f6.jpg)
