### ISSUE TITLE
Revisar e atualizar artefatos de Testes

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#117]
- Inserir Plano de Testes
- Inserir imagens comprovando testes realizados

**Comment by jjms2** [comment]
Foram encontradas dificuldades para a revisão do plano de testes tendo em vista  a origem dos requisitos para a criação dos casos de teste. Dessa forma há necessidade de explanar melhor a origem para que não haja retrabalho.

**Comment by jjms2** [comment]
Foram encontradas dificuldades também em relação à criação do teste JUnit do cadastro de usuário pois foi gerado uma exceção não tratada.

**Comment by jjms2** [comment]
Inclusão dos testes Selenium parcial.

**Comment by jjms2** [comment]
[Engenharia de Software - Testes Selenium.zip](https://github.com/thiagorainmaker77/blockbuster/files/2860291/Engenharia.de.Software.-.Testes.Selenium.zip)

**Comment by jjms2** [comment]
Erros na execução do teste de Exclusão de Filmes. O filme conforme tela abaixo não exclui. @thiagorainmaker77 verificar.
![resultado01 - erro na exclusao de filmes](https://user-images.githubusercontent.com/45432276/52711657-1dd7c280-2f71-11e9-8ed5-a886440ac23b.JPG)

**Comment by jjms2** [comment]
* Inserir Plano de Testes - Atualizado no Google Drive
* Inserir imagens comprovando testes realizados - Foi criado no Drive o relatório de testes com os testes realizados.

**Comment by fabianaferreiracardoso** [comment]
[Plano de Testes_17022019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2873690/Plano.de.Testes_17022019.pdf)

**Comment by fabianaferreiracardoso** [comment]
[Relatório de Testes_17022019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2873691/Relatorio.de.Testes_17022019.pdf)

**Comment by fabianaferreiracardoso** [comment]
Documentação completa está na pasta:

https://drive.google.com/drive/folders/1k4StopRJ03lo1wLdE1MtwauQ_Iw4W9cY
