### ISSUE TITLE
Atualizar relatório tecnico

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#118]
- Inserir dados sobre quarta iteração

**Comment by jjms2** [comment]
Inserido no relatório técnico a minha revisão individual no item 8.2.b.

**Comment by fabianaferreiracardoso** [comment]
[RELATORIO_TECNICO_BLOCKBUSTER_ver_25_01_vFinal (1).pdf](https://github.com/thiagorainmaker77/blockbuster/files/2877829/RELATORIO_TECNICO_BLOCKBUSTER_ver_25_01_vFinal.1.pdf)
