### ISSUE TITLE
Revisar e atualizar artefatos de testes

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#119]
Revisar e caso seja necessário atualizar TDD, relatório de testes e plano de testes

- CRUD de filme, cliente e funcionário.
- Locação de filme
- Controle de acesso à funcionalidades do sistema

**Comment by fabianaferreiracardoso** [comment]
Por gentileza inserir os artefatos comprovando o encerramento da revisão até o dia 06/02/2019

**Comment by fabianaferreiracardoso** [comment]
[PLANO_TESTES.docx](https://github.com/thiagorainmaker77/blockbuster/files/2868908/PLANO_TESTES.docx)

**Comment by jjms2** [comment]
Plano de testes criado e finalizado no Drive.

**Comment by jjms2** [comment]
[Plano de Testes_17022019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2873010/Plano.de.Testes_17022019.pdf)

**Comment by jjms2** [comment]
[Relatório de Testes_17022019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2873011/Relatorio.de.Testes_17022019.pdf)

**Comment by jjms2** [comment]
Os testes TDD da locação não foram implementados.

**Comment by fabianaferreiracardoso** [comment]
Documentação final apresentada na tarefa #117
