### ISSUE TITLE
Revisar implementação da funcionalidade de locação de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#121]
- Deverá verificar se houve alterações na users storie e diagramas da fase de análise e testes para atualizar a implementação já realizada.

**Comment by fabianaferreiracardoso** [comment]
[Documento de Requisitos - MPROF - Video Locadora Imperial.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2829632/Documento.de.Requisitos.-.MPROF.-.Video.Locadora.Imperial.pdf)

[Proposta de Projeto - Ciclo de Vida do Software.docx](https://github.com/thiagorainmaker77/blockbuster/files/2829635/Proposta.de.Projeto.-.Ciclo.de.Vida.do.Software.docx)

**Comment by fabianaferreiracardoso** [comment]
Requisitos a serem atendidos

RF01 - O sistema deve registrar locações, indicando o cliente e os itens locados, bem como a data e o valor da locação e a data de devolução prevista de cada item

RF03 - O sistema deve registrar os pagamentos de locação
- Os valores padrão das locações são dados pelo tipo de mídia do item sendo locado. Atualmente, são cobrados os seguintes valores: DVD, VHS e HD-DVD R$ 5,00, Blu-Ray R$ 7,50, sendo que lançamentos têm um acréscimo de 50% nos valores acima mencionados.

- O prazo de devolução é de um dia para lançamentos e três dias para filmes do catálogo. Contudo o valor a ser efetivamente pago e a data de devolução prevista de um item locado podem ser alterados pelo atendente da locadora para aplicar descontos individualizados ou ampliar prazos de devolução.

RN01 - O sistema deve permitir que sejam dados descontos nas locações, bem como que sejam ampliados os prazos de devolução de itens, em função da política da empresa.

RN04 - O sistema deve manter o histórico de locações e, portanto, clientes que tenham feito locações não poderão ser excluídos.

RN08 - Pagamentos podem ser feitos no ato da locação ou da devolução de um item. Caso uma locação de um item não tenha sido paga no ato da locação, terá de ser paga obrigatoriamente na devolução.

RN09- Pagamentos pode ser feitos em dinheiro, cheque ou cartão

RN11 O valor da locação de um item é dado pelo tipo de mídia do item. Cada tipo de mídia tem um valor de locação associado. Um acréscimo de 50% do valor da locação do tipo de mídia deve ser aplicado no caso do filme do item ser um lançamento.

RN 13 - Locações pagas não podem ser canceladas.

RN14 - A data de devolução prevista de um item locado deve ser superior à data da locação.

RN16 - Clientes em atraso não podem efetuar nem locações nem reservas

RNF08 - O sistema deve ser fácil de usar, devendo-se evitar a digitação desnecessária de informações, de modo a dar agilidade ao processo

RNF09 - O sistema deve ser fácil de manter, de modo a acomodar novas funcionalidades ou até mesmo adaptação para outras vídeo locadoras.

**Comment by Mars17** [comment]
Considerar que a locação é da midia do filme.
Importante permitir a flexibilidade da data de devolução, porém a data de locacão deva ser mantida.
A locação deverá ter valores calculados com base no tipo de mídia e se o filme seja lancamento ou não.

**Comment by Mars17** [comment]
Ver Diagrama de Sequencia:





![diagrama de sequencia basico 16](https://user-images.githubusercontent.com/7024700/52251161-8d4f1180-28e2-11e9-862f-ab74d23f0dd1.jpeg)

**Comment by thiagorainmaker77** [comment]
@Mars17 há a necessidade de refatorar o diagrama de classes de modo a comportar uma data de devolução para cada item;

@fabianaferreiracardoso crie por favor uma atividade para o @Mars17 solicitando a remodelagem do diagrama, e uma atividade para mim para a revisão do impacto desta mudança no sistema em funcionamento.

**Comment by thiagorainmaker77** [comment]
esta atividade só pode ser continuada apos as alterações solicitadas;

**Comment by Mars17** [comment]
Certo!

**Comment by thiagorainmaker77** [comment]
esta atividade foi fortemente impactada devido ao atraso na fase de analise e as mudanças ocorridas na relação entre locação e filme

**Comment by fabianaferreiracardoso** [comment]
A finalização da implementação dessa funcionalidade ficará para trabalhos futuros
