### ISSUE TITLE
Revisar implementação da funcionalidade gerenciamento de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#122]
- Revisar implementação da interfaces, classes, métodos e atributos da funcionalidade referente ao controle de cliente

**Comment by thiagorainmaker77** [comment]
@fabianaferreiracardoso realizar o **controle de distribuidoras de filmes** implica em ter um cadastro de distribuidora, não?

**Comment by fabianaferreiracardoso** [comment]
Diagramas foram corrigidos, entretanto o sprint foi encerrado. Será remanejado para trabalhos futuros.
