### ISSUE TITLE
Revisar implementação da funcionalidade gerenciamento de Cliente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#123]
Verificar e atualizar caso seja necessário a funcionalidade de gerenciamento de cliente de acordo com o documento de requisitos fornecido pelo cliente

**Comment by fabianaferreiracardoso** [comment]
A revisão e atualização deverá contemplar:

- Clientes locam filmes. Um cliente pode ser um cliente titular ou um de seus dependentes. Quando uma pessoa faz sua inscrição na locadora como titular, lhe é dado o direito de indicar até três dependentes, pelos quais será responsável.

- Para a locadora, é fundamental identificar exatamente quem locou uma fita, se o titular ou um de seus dependentes.

- Para efeito de controle, a locadora deseja ter mais informações sobre o titular do que sobre seus dependentes.

- Sobre titular, deseja-se saber nome, e-mail, endereço, telefone residencial, local onde trabalha, telefone comercial, telefone celular, sexo, CPF e data de nascimento. Apenas maiores de idade podem ser titulares.

- De um dependente, são necessários apenas o nome, e-mail, sexo e data de nascimento. Tanto titulares quanto dependentes têm um número de inscrição, o qual é único por cliente.

- Clientes podem também reservar filmes. 

RF 09 - O sistema deve permitir o gerenciamento do conjunto de clientes da locadora, abrangendo tanto clientes titulares quanto seus dependentes.

RF 10 - O sistema deve permitir desativar clientes

RF 11 - O sistema deve permitir reativar clientes

**Comment by fabianaferreiracardoso** [comment]
O prazo de encerramento dessa atividade é dia 10/02/2019

**Comment by fabianaferreiracardoso** [comment]
Deverá ser verificado os artefatos gerados nas disciplinas de análise e testes. Caso ocorram divergências as mesmas deverão ser relatadas no whatsapp

**Comment by Mars17** [comment]
Considerar a possibilidade de ativar ou desativar cadastro de cliente.
Caso o Cliente seja **titular** e Funcionario efetue a desativação da conta os Dependentes atrelados ao titular também serão desativados.

Caso o Cliente seja **titular** e Funcionario efetue a ativação da conta os Dependentes atrelados ao titular também serão desativados.

Caso o Cliente seja **dependente**  e Funcionario efetue a ativação da conta os titular se matem ativo

**Comment by thiagorainmaker77** [comment]
@Mars17 @fabianaferreiracardoso Onde posso encontrar o diagrama de sequência desta atividade?

**Comment by fabianaferreiracardoso** [comment]
Marcello por gentileza apresentar o link de acesso ao diagrama de sequencia
