### ISSUE TITLE
Criar vídeos demonstrando testes automatizados de software

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#129]
- Apresentar os vídeos feito comprovando a automatização dos testes

**Comment by jjms2** [comment]
Vídeos implementados e postados no Youtube. Os links foram colocados no repositórios de vídeos do Wiki do Git.

https://github.com/thiagorainmaker77/blockbuster/wiki/7.-V%C3%ADdeos-do-Projeto
