### ISSUE TITLE
Revisão do impacto na mudança da funcionalidade de locação de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#132]
- Avaliar o impacto da alteração da atividade #121 no software já em funcionamento

**Comment by Mars17** [comment]
![untitled diagram 3 2](https://user-images.githubusercontent.com/7024700/52721201-51761500-2f90-11e9-9ddf-64971ad6682a.jpg)

Diagrama Refatorado

**Comment by thiagorainmaker77** [comment]
alterações realizadas, o impacto foi relativamente pequeno
