### ISSUE TITLE
Correção do erro na funcionalidade exclusão de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#133]
- Erro apresentado na issues #117

**Comment by thiagorainmaker77** [comment]
@jjms2 o erro no teste ocorreu por conta da tentativa de cadastrar um filme contendo uma locação;

**Comment by jjms2** [comment]
O erro persiste mesmo com o cadastro de um novo filme sem locação. Acredito que deve haver algum problema na realização do filtro do filme a ser excluído.
