### ISSUE TITLE
Atualizar Mockups do Projeto

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#135]
- Inserir as telas de prototipação

**Comment by fabianaferreiracardoso** [comment]
[MOCKUPS-20190215T112556Z-001.zip](https://github.com/thiagorainmaker77/blockbuster/files/2869064/MOCKUPS-20190215T112556Z-001.zip)

**Comment by Mars17** [comment]
Tela Correpondente a Cadastro de Distribuidora
![blockonline - cadastro distribuidora](https://user-images.githubusercontent.com/7024700/52876656-fe8e9000-313e-11e9-8bc0-9a250f3fc185.png)
