### ISSUE TITLE
Criar manual do usuário para a tela de cadastro de cliente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#21]

**Comment by Mars17** [comment]
[Manual do Usuário.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2660154/Manual.do.Usuario.pdf)

Manual do Usuário da Primeira Sprint

**Comment by Mars17** [comment]
[Manual do Usuário.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2660162/Manual.do.Usuario.pdf)

Manual Primeira Sprint

**Comment by Mars17** [comment]
[Manual do Usuário.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2660167/Manual.do.Usuario.pdf)

Manual do Usuário, primeira sprint

**Comment by Mars17** [comment]
[Manual do Usuário.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2660169/Manual.do.Usuario.pdf)

Manual Editado
