### ISSUE TITLE
Criar histórias de usuários para o cadastro de cliente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#27]

**Comment by Mars17** [comment]
[Historia-Cliente.txt](https://github.com/thiagorainmaker77/blockbuster/files/2653286/Historia-Cliente.txt)

**Comment by Mars17** [comment]
![cadastro cliente](https://user-images.githubusercontent.com/7024700/49661755-1821a600-fa31-11e8-9127-5ebcfe2d20c2.png)

**Comment by Mars17** [comment]
![cliente](https://user-images.githubusercontent.com/7024700/49661806-40110980-fa31-11e8-99c9-8393f0a5d846.png)
