### ISSUE TITLE
Implementar o CRUD de filmes

### ISSUE THREAD

**Issue by thiagorainmaker77** [thiagorainmaker77/blockbuster#3]
criar a implementação de código para cadastrar, listar, alterar e deletar os filmes

Atende completamente o requisito:

[RF06] | Controle do acervo da locadora

**Comment by fabianaferreiracardoso** [comment]
Por gentileza acrescentar a seguinte regra na funcionalidade cadastro de filmes:
[RF13] - Não permitir o cadastro de filmes com classificação de uma estrela

**Comment by thiagorainmaker77** [comment]
![junit_filme](https://user-images.githubusercontent.com/44616457/49660806-42ba3180-fa26-11e8-9737-8ed823b35b79.png)


JUnit executou de boa. só estou com aquele problema com o heroku, portanto, a classe vai ficar comentada.
