### ISSUE TITLE
Criar diagrama de sequencia para cliente

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#33]

**Comment by Mars17** [comment]
![whatsapp image 2018-12-05 at 17 48 13](https://user-images.githubusercontent.com/7024700/49549789-ea255000-f8d0-11e8-82fb-245b485eee56.jpeg)
![whatsapp image 2018-12-05 at 17 48 30](https://user-images.githubusercontent.com/7024700/49549793-ed204080-f8d0-11e8-920a-6f621a38ad0e.jpeg)
![whatsapp image 2018-12-05 at 17 49 00](https://user-images.githubusercontent.com/7024700/49549796-f01b3100-f8d0-11e8-80c1-e276585d956b.jpeg)

Diagrama de Sequencia - Cadastro, Atualização e Exclusão
