### ISSUE TITLE
Implementar o CRUD de clientes

### ISSUE THREAD

**Issue by thiagorainmaker77** [thiagorainmaker77/blockbuster#4]
criar as estruturas de insert, select, update e delete relacionados a entidade Cliente

Atendendo ao requisito

[RF09] | Gerenciamento do conjunto de clientes da locadora, abrangendo tanto clientes titulares quanto seus dependentes.

**Comment by repositoriomestrado** [comment]
@fabianaferreiracardoso  e @Mars17 como podemos definir a senha padrão para um usuário?

**Comment by fabianaferreiracardoso** [comment]
Pode definir os 7 primeiros caracteres do CPF

**Comment by thiagorainmaker77** [comment]
uma dúvida. vai ser necessário o cliente logar no sistema? se sim, expliquem por favor o motivo.

**Comment by jjms2** [comment]
ok @thiagorainmaker77 @fabianaferreiracardoso @Mars17 , para o próximo sprint precisamos de uma tarefa que impedir que um cliente seja dependente dele mesmo, e que um dependente tenha outros dependentes
