### ISSUE TITLE
Criar visão do modelo de implantação

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#55]
Criar diagrama com descrição de cada solução usada na implantação do software.

**Comment by thiagorainmaker77** [comment]
@fabianaferreiracardoso não entendi bem esta tarefa, ela já não foi atendida na atividade #69 ?

**Comment by fabianaferreiracardoso** [comment]
[PROJETO_ARQUITETURAL(1).pdf](https://github.com/thiagorainmaker77/blockbuster/files/2696591/PROJETO_ARQUITETURAL.1.pdf)
