### ISSUE TITLE
Criar CRUD Usuario (Funcionario)

### ISSUE THREAD

**Issue by Mars17** [thiagorainmaker77/blockbuster#59]
Complexidade: Media
Disciplina: Eg. Software
Fase: Implementação

**Comment by thiagorainmaker77** [comment]
@Mars17 removi o método alterarStatus(Funcionario f) da interface FuncionarioBCI, pois a ação já é contemplada no update

**Comment by Mars17** [comment]
Segue em desenvolvimento

**Comment by fabianaferreiracardoso** [comment]
Jefferson como estão os testes dessa funcionalidade?
