### ISSUE TITLE
Implementar a funcionalidade de locação de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#63]
- Pagamento de locação
- Escolha de filme
- Histórico de locação

**Comment by fabianaferreiracardoso** [comment]
Esta funcionalidade deverá ser construída a partir dos seguintes requisitos:

[RF01] - Registro de locações, indicando o cliente e os itens locados, bem como a data e o valor da locação e a data de devolução prevista de cada item. 

De um dado filme, a locadora pode possuir vários itens, em diferentes mídias, tais como DVD, VHS, BluFRay,HDFDVD. Os filmes são itens, em diferentes mídias, tais como DVD, VHS, BluFRay, HD-DVD. Os filmes são classificados nos seguintes gêneros: ação, animação, aventura, comédia, documentário, drama, ficção, guerra, musical, policial, romance, suspense e terror. Além disso, a locadora faz distinção entre filmes de catálogo e lançamentos.

[RN01] - Dar descontos nas locações, bem como que sejam ampliados os prazos de devolução de itens, em função da política da empresa.

Os valores padrão das locações são dados pelo tipo de mídia do item sendo locado. Atualmente, são cobrados os seguintes valores: DVD, VHS e HDF DVD – R$5,00; BluRay– R$ 7,50, sendo que lançamentos têm um acréscimo de 50% nos valores acima mencionados. O prazo para devolução é de um dia para  lançamentos e três dias para filmes do catálogo. Contudo, o valor a ser efetivamente pago e a data de devolução prevista de um item locado podem ser  alterados pelo atendente da locadora para aplicar descontos individualizados ou
ampliar prazos de devolução.

[RN04] - Manter o histórico de locações e,portanto, clientes que tenham feito locações não poderão ser excluídos.

[RN11] - O valor da locação de um item é dado pelo tipo de mídia do item. Cada tipo de mídia tem um valor de locação associado. Um acréscimo de 50% do valor da locação do tipo de mídia deve ser aplicado no caso do filme do item a ser lançado.

[RN12] - A data de devolução prevista é definida em função do filme do item ser lançamento ou não." Lançamentos têm prazo de um dia; filmes do catálogo têm três dias de prazo.

[RN13] - Locações pagas não podem ser canceladas.

[RN14] - A data de devolução prevista de um item locado deve ser superior à data da locação.

[RN16] - Clientes em atraso não podem efetuar nem locações nem reservas.

[RNF08] - O sistema deve ser fácil de usar, devendo se evitar a digitação  desnecessária de informações, de modo a dar agilidade ao processo.

[RNF09] - O sistema deve ser fácil de manter, de modo a acomodar novas funcionalidades, ou, até, mesmo, adaptação, para, outras, vídeo, locadoras.

**Comment by thiagorainmaker77** [comment]
foram feitas algumas alterações na interface LocacaoBCI para adequar ao modelo

**Comment by thiagorainmaker77** [comment]
@fabianaferreiracardoso @Mars17 sugiro a criação de uma outra atividade, a qual se refere aos valores dos filmes. 

um cadastro de tipos de mídia e os respectivos valores a serem cobrados em cada tipo de locação, tornando assim o valor de uma locação um dado derivado dos valores dos produtos associados a esta locação.

Sugiro ainda que esta atividade sugerida preceda a atividade de locação, fazendo assim uma readequação do sprint atual.

**Comment by thiagorainmaker77** [comment]
Acabei de finalizar a atividade de locação do filme. @fabianaferreiracardoso sugiro que esta tarefa seja dividida em mais duas: 1 - para implementar calculo de valor da locação, pois temos que levar em conta possíveis variações futuras; 2 - a atividade de gravar a locação no banco;


para o próximo sprint sugiro que criemos uma tela de controle de locação também;

**Comment by fabianaferreiracardoso** [comment]
Excelente idéia colega vamos fazer isso

**Comment by fabianaferreiracardoso** [comment]
Verifiquei que está aparecendo a mensagem de locação realizada com sucesso mesmo não selecionando o cliente e o filme

**Comment by fabianaferreiracardoso** [comment]
Marcelo por favor insira os mockups, users stories e diagramas de sequencias com as alterações

**Comment by fabianaferreiracardoso** [comment]
Jefferson por gentileza insira os testes realizados dessa funcionalidade

**Comment by fabianaferreiracardoso** [comment]
O prazo é até hoje para que Thiago possa dar andamento na finalização da funcionalidade

**Comment by thiagorainmaker77** [comment]
@fabianaferreiracardoso com relação a locação mesmo sem cliente, vamos criar uma atividade de correção para o próximo sprint. é algo bem simples de fazer.

**Comment by fabianaferreiracardoso** [comment]
Estarei remanejando essa atividade para o quarto sprint para discutirmos a melhor forma de implementá-la.
