### ISSUE TITLE
Criar user stories para locação de filme

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#64]

**Comment by fabianaferreiracardoso** [comment]
Marcelo por favor verificar a tarefa
https://github.com/thiagorainmaker77/blockbuster/issues/85

**Comment by fabianaferreiracardoso** [comment]
Marcelo quando tiver condições coloque a users stories dessa funcionalidade aqui para encerrarmos a atividade.

**Comment by Mars17** [comment]
**Sumário:** Locação de mídias por um cliente.

**Ator Primário:** Funcionário 
**Pré-condições:** O funcionário fez login no sistema. O cliente está cadastrado no sistema.

**Fluxo Principal:**
1.  O funcionário solicita o locar a mídia.
2.	O sistema abre uma interface solicitando o nome do Cliente, o nome do filme, Data da Locação e Data de Devolução e os campos respectivos para receber as informações a serem fornecidas pelo funcionário.
3.	O funcionário fornece cada uma das informações solicitadas e clica ok.
4.	O sistema salva todas as informações e mostra uma interface com as seguintes informações: Código da Locação, Nome do Cliente, Código do Vídeo, Título do Vídeo, Valor da Locação, Data da Locação e Data da Devolução e termina o caso de uso.

**Fluxo Alternativo:** Cancelar Locação
a.	Se o funcionário clicar em cancelar e o caso de uso termina. Fluxos de Exceção (4): Campo obrigatório vazio.

**Fluxos de Exceção:**

 _Campo obrigatório vazio_
a.	Se o funcionário não preencher os seguintes campos obrigatórios: nome do Cliente e o nome do vídeo, o caso de uso exibirá uma mensagem informando o erro.
b.	O funcionário corrige o erro e clica ok.
c.	O sistema executa o passo 4.

_Midia já Locada, não disponivel._
a.	Se o sistema identificar que a mídia já foi locada, exibe uma mensagem de erro.
b.	O funcionário troca o código.
c.	O sistema realiza o passo 4.

_Cliente não Encontrado na base de dados_
a.	Se não for encontrado o nome do cliente o sistema vai exibir uma mensagem desse erro e volta para o passo 2.

_Midia não encontrada_
a.	Se não for encontrado o titulo da mídia , o sistema vai exibir uma mensagem desse erro e volta para o passo 2.

**Pós-condições:** O sistema salva o registro da locação no banco de dados.

**Comment by Mars17** [comment]
**Sumário:** Locação de mídias por um cliente.

**Ator Primário:** Funcionário
**Pré-condições:** O funcionário fez login no sistema. O cliente está cadastrado no sistema.

**Fluxo Principal:**

O funcionário solicita o locar a mídia.
O sistema abre uma interface solicitando o nome do Cliente, o nome do filme, Data da Locação e Data de Devolução e os campos respectivos para receber as informações a serem fornecidas pelo funcionário.
O funcionário fornece cada uma das informações solicitadas e clica ok.
O sistema salva todas as informações e mostra uma interface com as seguintes informações: Código da Locação, Nome do Cliente, Código do Vídeo, Título do Vídeo, Valor da Locação, Data da Locação e Data da Devolução e termina o caso de uso.

**Fluxo Alternativo:** Cancelar Locação
a.	Se o funcionário clicar em cancelar e o caso de uso termina. 

**Fluxos de Exceção:**

_Campo obrigatório vazio_
a.	Se o funcionário não preencher os seguintes campos obrigatórios: nome do Cliente e o nome do vídeo, o caso de uso exibirá uma mensagem informando o erro.
b.	O funcionário corrige o erro e clica ok.
c.	O sistema executa o passo 4.

_Midia já Locada, não disponivel._
a.	Se o sistema identificar que a mídia já foi locada, exibe uma mensagem de erro.
b.	O funcionário troca o código.
c.	O sistema realiza o passo 4.

_Cliente não Encontrado na base de dados_
a.	Se não for encontrado o nome do cliente o sistema vai exibir uma mensagem desse erro e volta para o passo 2.

_Midia não encontrada_
a.	Se não for encontrado o titulo da mídia , o sistema vai exibir uma mensagem desse erro e volta para o passo 2.

**Pós-condições:** O sistema salva o registro da locação no banco de dados.
