### ISSUE TITLE
Implementar cadastro de tipos de mídia e os respectivos valores a serem cobrados em cada tipo de locação.

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#72]
Tornar o valor de uma locação um dado derivado dos valores dos produtos associados a esta locação.

**Comment by fabianaferreiracardoso** [comment]
De um dado filme, a locadora pode possuir vários itens, em diferentes mídias, tais como DVD, VHS, BluFRay,HDFDVD. Os filmes são itens, em diferentes mídias, tais como DVD, VHS, BluFRay, HD-DVD. Os filmes são classificados nos seguintes gêneros: ação, animação, aventura, comédia, documentário, drama, ficção, guerra, musical, policial, romance, suspense e terror. Além disso, a locadora faz distinção entre filmes de catálogo e lançamentos.

**Comment by fabianaferreiracardoso** [comment]
Os valores padrão das locações são dados pelo tipo de mídia do item sendo locado. Atualmente, são cobrados os seguintes valores: DVD, VHS e HDF DVD – R$5,00; BluRay– R$ 7,50, sendo que lançamentos têm um acréscimo de 50% nos valores acima mencionados. O prazo para devolução é de um dia para lançamentos e três dias para filmes do catálogo. Contudo, o valor a ser efetivamente pago e a data de devolução prevista de um item locado podem ser alterados pelo atendente da locadora para aplicar descontos individualizados ou ampliar prazos de devolução.

**Comment by Mars17** [comment]
Terei que mudar  o diagrama de sequencia de locação, especificando o tipo de  midia.
Pelo que entendi, terá que ter um indicador pra considerar que o filme é lançamento  ou não, subtendi-se que terá um metodo que calcule isso.

**Comment by fabianaferreiracardoso** [comment]
Quando finalizar insira o novo diagrama, Mockups e users stories

**Comment by fabianaferreiracardoso** [comment]
Jefferson conferir as alterações e registrar os testes realizados.

**Comment by fabianaferreiracardoso** [comment]
Artefatos disponibilizados no Google driver
