### ISSUE TITLE
Conferir os marcos do projeto

### ISSUE THREAD

**Issue by fabianaferreiracardoso** [thiagorainmaker77/blockbuster#95]
- Validar os pontos de controle do projeto

**Comment by fabianaferreiracardoso** [comment]
Cobrar a finalização das atividades referentes aos sprints anteriores.

**Comment by fabianaferreiracardoso** [comment]
Foi dado um prazo até sext-feira (25/01/2019) para que as atividades de  análise e design juntamente com os testes fossem encerradas. Até o presente momento (28/01/2019) as atividades estão pendentes.
Convoco uma reunião para hoje (28/01/2019) às 20 h para tratar os próximos passos.

**Comment by Mars17** [comment]
Bom dia, gostaria de saber quais atividades estão pendentes. Acredito que todas a atividades incumbidas a mim, tais como analise e design, foram entregues. Sendo assim, é importante descriminar quais sejam estas atividades para que possamos discutir logo mais a noite.

**Comment by fabianaferreiracardoso** [comment]
[Pendências do Projeto Blockbuster-28012019.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2807303/Pendencias.do.Projeto.Blockbuster-28012019.pdf)

**Comment by fabianaferreiracardoso** [comment]
[Marcos_do_Projeto.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2807414/Marcos_do_Projeto.pdf)

**Comment by fabianaferreiracardoso** [comment]
[Marcos_do_Projeto.pdf](https://github.com/thiagorainmaker77/blockbuster/files/2818357/Marcos_do_Projeto.pdf)
